# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Welcome to Jekyll!

# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Apache Airflow
description: > # this means to ignore newlines until "baseurl:"
  Airflow is a platform to programmatically author, schedule and monitor workflows.
  Use airflow to author workflows as directed acyclic graphs (DAGs) of tasks. The airflow scheduler executes your tasks on an array of workers while following the specified dependencies. Rich command line utilities make performing complex surgeries on DAGs a snap. The rich user interface makes it easy to visualize pipelines running in production, monitor progress, and troubleshoot issues when needed.
  When workflows are defined as code, they become more maintainable, versionable, testable, and collaborative.

# input directory
source: src

# the base hostname & protocol for your site
url: "https://airflow.apache.org"

twitter_username: apacheairflow

# Build settings
markdown: kramdown

collections:

# Things to include that are subdirectories created by sphinx
include: ['_static', '_modules', '_sources', '.htaccess']

# Things to ignore in the build
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

# Don't use the page title in the table of contents
highlighter: rouge

kramdown:
  toc_levels:     2..6

# The most recent release of Airflow.
release_latest: 1.10.2

# Plugins are configured in the Gemfile.

# Set the time zone for site generation, fixed to US Pacific Time
timezone: America/Los_Angeles

